In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("indian_liver_patient.csv") # Data can be found here: https://github.com/611noorsaeed/Liver-Disease-Predictor/blob/main/indian_liver_patient.csv

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    object
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  579 non-null    float64
 10  Dataset                     583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [ ]:
df.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

# Exploring the Dataset

In [ ]:
df.isnull().sum() # Let us verify the presence of null values in the dataset

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [ ]:
# we can see from the output above that the feature 'Albumin_and_Globulin_Ratio' has 4 blanks.

In [ ]:
# time to drop the blank values.

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.shape

(579, 11)

In [ ]:
df.duplicated().sum()

np.int64(13)

In [ ]:
# We can see that 13 records are duplicated.

In [ ]:
df.drop_duplicates(inplace = True)

# Encoding

## Gender is a categorical feature with values Male and Female

## To deal with this, we convert into numeric form using Label Encoding Or One-Hot Encoding

## Our goal is to assign Male with Encoded value '1' and Female with Encoded value '2'.

In [ ]:
encoder = LabelEncoder()

In [ ]:
df['Gender'] = encoder.fit_transform(df['Gender'])
df.head(2)

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,0,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,1,10.9,5.5,699,64,100,7.5,3.2,0.74,1

In [ ]:
# We observe the output of df.head() to confirm the encoding process.

In [ ]:
# We now move onto scaling the feature.

# Feature Scaling

In [ ]:
# Our goal is to make sure that our algorithm does not treat larger numbers as more important.
# To do so, we scale all features/columns, except for the target column.

In [ ]:
features = ["Age", "Total_Bilirubin",	"Direct_Bilirubin",	"Alkaline_Phosphotase",	"Alamine_Aminotransferase",	"Aspartate_Aminotransferase",	"Total_Protiens",	"Albumin",	"Albumin_and_Globulin_Ratio"]

scaler = StandardScaler()

df[features] = scaler.fit_transform(df[features]) # this is to scale all the features we defined in variable features through standard scaling.

In [ ]:
df.head(3)

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,1.236928,0,-0.420124,-0.495190,-0.429625,-0.352659,-0.315148,0.280819,0.194225,-0.150315,1
1,1.052432,1,1.203777,1.406906,1.654054,-0.088755,-0.033926,0.925059,0.068445,-0.651328,1
2,1.052432,1,0.630636,0.913770,0.803490,-0.110747,-0.143671,0.464887,0.194225,-0.181628,1

In [ ]:
# Next, we balance the data, so the classes are balanced so one class is
# not given more importance over the others.

# Data Balancing

In [ ]:
from imblearn.over_sampling import SMOTE # SMOTE replicates the minority classes
# until the minority and majority classes are equally balanced.

X = df.drop('Dataset' ,axis = 1)
y = df['Dataset']

smote = SMOTE()

# X_resampled constitutes the input features
# y_resampled constitutes the target features

X_resampled, y_resampled = smote.fit_resample(X,y)

y_resampled.value_counts()

Dataset
1    404
2    404
Name: count, dtype: int64

# Splitting The Data Into Training And Testing Data

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size = 0.2, random_state = 42)

# Measuring Predictions Through Logistic Regression, Random Forest, SVC

# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\n\n", classification_report(y_test, y_pred))
print("\n\n", confusion_matrix(y_test, y_pred))

               precision    recall  f1-score   support

           1       0.77      0.58      0.66        76
           2       0.70      0.85      0.76        86

    accuracy                           0.72       162
   macro avg       0.73      0.71      0.71       162
weighted avg       0.73      0.72      0.72       162



 [[44 32]
 [13 73]]

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

model_r = RandomForestClassifier()

model_r = model_r.fit(X_train, y_train)

y_pred = model_r.predict(X_test)

print("\n\n", classification_report(y_test, y_pred))
print("\n\n", confusion_matrix(y_test, y_pred))

               precision    recall  f1-score   support

           1       0.81      0.75      0.78        76
           2       0.79      0.85      0.82        86

    accuracy                           0.80       162
   macro avg       0.80      0.80      0.80       162
weighted avg       0.80      0.80      0.80       162



 [[57 19]
 [13 73]]

# SVC

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

model = SVC()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\n\n", classification_report(y_test, y_pred))
print("\n\n", confusion_matrix(y_test, y_pred))

               precision    recall  f1-score   support

           1       0.79      0.61      0.69        76
           2       0.71      0.86      0.78        86

    accuracy                           0.74       162
   macro avg       0.75      0.73      0.73       162
weighted avg       0.75      0.74      0.74       162



 [[46 30]
 [12 74]]

# Creating an Inference Prediction System

In [ ]:
np.array([df.iloc[0,:-1]])

array([[ 1.23692766,  0.        , -0.42012372, -0.49518965, -0.4296251 ,
        -0.35265945, -0.31514841,  0.28081866,  0.19422491, -0.15031499]])

In [ ]:
# Test 1

import numpy as np

pred = model_r.predict(np.array([df.iloc[0,:-1]]))

if pred[0] == 1:
  print ("Liver Disease")
else:
  print("No Liver Disease")

Liver Disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
# Test 2

import numpy as np

pred = model_r.predict(np.array([df.iloc[23,:-1]]))

if pred[0] == 1:
  print ("Liver Disease")
else:
  print("No Liver Disease")

No Liver Disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(